### ISSUE TITLE
KeyError: '>' results in truncated vcf output

### ISSUE THREAD

**Issue by slyahn** [liguowang/CrossMap#11]
Hi,

I am trying to liftover a vcf from GRCh37 to GRCh38 and I get KeyError: '>' after a minute of running. I get some output for chromosome 1 to the vcf and the unmap files, but I expect output for all chromosomes.

I have used CrossMap v 0.3.4 and 0.4.0 and chain files from ensembl and ucsc, all result in this KeyError.

**Comment by slyahn** [comment]
Traceback (most recent call last):
  File "/home/syahn/.local/bin/CrossMap.py", line 1929, in <module>
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = sys.argv[2], refgenome = genome_file)
  File "/home/syahn/.local/bin/CrossMap.py", line 608, in crossmap_vcf_file
    fields[4] = revcomp_DNA(fields[4], True)
  File "/home/syahn/.local/bin/CrossMap.py", line 106, in revcomp_DNA
    return ''.join([complement[base] for base in reversed(seq)])
  File "/home/syahn/.local/bin/CrossMap.py", line 106, in <listcomp>
    return ''.join([complement[base] for base in reversed(seq)])
KeyError: '>'

**Comment by liguowang** [comment]
This probably means you have ">" character in the REF (4th-column) or the ALT (5th column) field. When CrossMap failed to reverse complement ">", it raised an error.

**Comment by slyahn** [comment]
You're right. I needed to remove structural variants from my vcf, which contain "<" and ">" characters. CrossMap is running smoothly now. Thanks so much!

**Comment by fidibidi** [comment]
Hi Slyahn 
I found this comment and was hoping you could share how you removed the structural variants that were causing your issues! It seems like I might be having the same thing... 

chr1	10056	DUP00000000	A	<DUP>

Above, is a read from my vcf.  Should I just replace any instance of the alt with a blank? 
Any thoughts would be super appreciated! 
Thanks!
