### ISSUE TITLE
Feature Request: Update SV  INFO/END field during liftover of  VCF

### ISSUE THREAD

**Issue by jjfarrell** [liguowang/CrossMap#15]
Structural Variants will often have an INFO/END field to indicate the end of a deletion. Presently CrossMap does not update this INFO field. So one will get and END value that is before  the start which is problematic. The GIAB SV Benchmark vcf is an example of where this is an issue:  
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz

**Comment by liguowang** [comment]
Thanks a lot. Will address this issue soon. 

Liguo

**Comment by liguowang** [comment]
v0.4.3 was released.

**Comment by jjfarrell** [comment]
Thanks for the quick response. I just tried update to the new 4.3 version but it appears to be installing v4.2 not v4.3.  

pip3  install --user git+https://github.com/liguowang/CrossMap.git
Collecting git+https://github.com/liguowang/CrossMap.git
  Cloning https://github.com/liguowang/CrossMap.git to /scratch/pip-req-build-7rf_r0fw
Requirement already satisfied: cython>=0.17 in /share/pkg/anaconda3/5.2.0/install/lib/python3.6/site-packages (from CrossMap==0.4.2) (0.28.3)
Requirement already satisfied: pysam in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from CrossMap==0.4.2) (0.15.4)
Requirement already satisfied: bx-python in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from CrossMap==0.4.2) (0.8.8)
Requirement already satisfied: pyBigWig in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from CrossMap==0.4.2) (0.3.17)
Requirement already satisfied: six in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from bx-python->CrossMap==0.4.2) (1.11.0)
Requirement already satisfied: numpy in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from bx-python->CrossMap==0.4.2) (1.16.4)
Building wheels for collected packages: CrossMap
  Building wheel for CrossMap (setup.py) ... done
  Stored in directory: /scratch/pip-ephem-wheel-cache-3x5beqov/wheels/62/b7/c7/8b9e7d911ae84ddbfbddd3b1675a8ba4f5a4e6ea5247d2ed03
Successfully built CrossMap
Installing collected packages: CrossMap
  Found existing installation: CrossMap 0.4.1
    Uninstalling CrossMap-0.4.1:
      Successfully uninstalled CrossMap-0.4.1
Successfully installed CrossMap-0.4.2

**Comment by liguowang** [comment]
please try: pip3 install CrossMap

**Comment by jjfarrell** [comment]
Same result. 
 pip3 install --user crossmap
```
Requirement already satisfied: crossmap in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (0.4.2)
Requirement already satisfied: cython>=0.17 in /share/pkg/anaconda3/5.2.0/install/lib/python3.6/site-packages (from crossmap) (0.28.3)
Requirement already satisfied: pysam in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from crossmap) (0.15.4)
Requirement already satisfied: bx-python in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from crossmap) (0.8.8)
Requirement already satisfied: pyBigWig in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from crossmap) (0.3.17)
Requirement already satisfied: numpy in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from bx-python->crossmap) (1.16.4)
Requirement already satisfied: six in /usr3/bustaff/farrell/.local/lib/python3.6/site-packages (from bx-python->crossmap) (1.11.0)
```

**Comment by liguowang** [comment]
Sorry, if you already have CrossMap installed.  You need to use (--upgrade):

$ pip3 install CrossMap --upgrade

Collecting CrossMap
  Downloading CrossMap-0.4.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 553 kB/s
Requirement already satisfied, skipping upgrade: bx-python in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from CrossMap) (0.8.4)
Requirement already satisfied, skipping upgrade: pysam in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from CrossMap) (0.15.2)
Requirement already satisfied, skipping upgrade: cython>=0.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from CrossMap) (0.29.11)
Requirement already satisfied, skipping upgrade: pyBigWig in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from CrossMap) (0.3.17)
Requirement already satisfied, skipping upgrade: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from bx-python->CrossMap) (1.12.0)
Requirement already satisfied, skipping upgrade: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from bx-python->CrossMap) (1.16.2)
Installing collected packages: CrossMap
  Attempting uninstall: CrossMap
    Found existing installation: CrossMap 0.4.2
    Uninstalling CrossMap-0.4.2:
      Successfully uninstalled CrossMap-0.4.2
Successfully installed CrossMap-0.4.3

**Comment by jjfarrell** [comment]
Thanks! I am now upgraded.
