### ISSUE TITLE
hg19ToGRCh37.over.chain.gz

### ISSUE THREAD

**Issue by hsiaoyi0504** [liguowang/CrossMap#16]
Previously, CrossMap hosts a chain file that can be used to convert vcfs from hg19 to GRCh37.
Later, this file has been removed due to the license issue of UCSC.
However, that file is not actually hosted by UCSC. Is there a way that we can download it from or generate manually?
Thank you.

**Comment by liguowang** [comment]
Hi, 
The links to download UCSC/Ensembl chain files are listed here: https://crossmap.readthedocs.io/en/latest/#chain-file
 Some old version of CrossMap could convert hg19 to GRCh37, but the latest version will not do this.

**Comment by hsiaoyi0504** [comment]
Thanks !
