### ISSUE TITLE
Feature request: Add flag to not break input intervals

### ISSUE THREAD

**Issue by bredeson** [liguowang/CrossMap#2]
Hi CrossMap Devs,

I would like to request an optional boolean flag that would tell CrossMatch not to break input feature intervals up into smaller intervals in the output (or move them to the `.unmap` file) if there is an indel in the chain file. Breaking features (or throwing them out) is not always desired; for example, a "gene" feature may span many such indels, yet the "exon" and/or "CDS" features of that gene may not intersect any indels themselves (the indels might intersect introns, instead).

Best,
Jessen

**Comment by liguowang** [comment]
We will consider adding this option (which is not trivial). One alternative solution is making a customized chain file that ignores the indels.

**Comment by bredeson** [comment]
Hi @liguowang, 
Thank you for your prompt reply! Unfortunately, if one were to make a chain file without the indels, the coordinates of the input features will be incorrectly mapped onto the new reference (when the alignments/chain records are not 100% similar). I guess an alternative is to break the alignments at every indel, so that every chain record represents only alignments with matches/mismatches, but how will CrossMap handle feature intervals that map to different chain records (e.g., when a gene feature intersects 2+ chains)?

Best,
-Jessen

**Comment by liguowang** [comment]
The new "CrossMap.py region" command has an option "-r" (The minimum ratio of bases that must be remaped) will be helpful, as this allows fuzzy mapping.
