### ISSUE TITLE
Feature request: option to compress liftovered vcf file

### ISSUE THREAD

**Issue by dwuab** [liguowang/CrossMap#20]
In the current version (0.5.1), the default behavior of CrossMap vcf is to output vcf uncompressed. This could be a problem when the input vcf file contains a large number of variants and/or samples. It will be great to add an option for compressing the vcf output to CrossMap.

**Comment by liguowang** [comment]
this option would be easy to add.

Thanks

Liguo

**Comment by liguowang** [comment]
add the "--compress" flag in version 0.5.2
