### ISSUE TITLE
Option to not change reference allele when liftovering vcf files

### ISSUE THREAD

**Issue by dwuab** [liguowang/CrossMap#23]
According to documentation, CrossMap will update chromosomes, genomic coordinates and reference allele when performing liftover of vcf files and liftover will fail if the reference allele is the same as the alternative allele (or one of the alternative alleles?).

Take rs657152 as an example, its reference allele is different in GRCh37 and GRCh38. In our b37 callset, it was called as a bi-allelic allele C->A, and therefore it cannot be liftovered because the reference allele in GRCh38 is A. However, due to the interest in rs657152 (ABO gene), I wish this snp could be rescued when liftover.

My suggestion is to add an new option to not change reference allele when performing liftover, and let other tools such as bcftools to take care of the swapping of reference and alternative alleles.

**Comment by liguowang** [comment]
It makes sense, we will release a new version soon.

Thanks

Liguo

**Comment by liguowang** [comment]
add the "--no-comp-alleles" flag in version 0.5.2
