### ISSUE TITLE
error outputting bigwig file

### ISSUE THREAD

**Issue by xavdartagnan** [liguowang/CrossMap#3]
Hello,
I had an issue with some bigwig files that were generated with our chip-seq pipeline.
I suspect it may be because of the way our bigwig files are formatted. But they are fine for example to use for plotting heatmaps using deeptools.

the error is as follows:
CrossMap.py bigwig hg38ToHg19.over.chain.gz nameA.bw nameB
@ 2019-05-02 13:15:45: Read chain_file:  hg38ToHg19.over.chain.gz
@ 2019-05-02 13:15:47: Liftover bigwig file: nameA.bw ==>nameB.bgr
@ 2019-05-02 13:50:38: Merging overlapped entries in bedGraph file ...
@ 2019-05-02 13:50:38: Sorting bedGraph file:nameB.bgr

Traceback (most recent call last):
  File "/home/xavier/.local/bin/CrossMap.py", line 1718, in <module>
    crossmap_wig_file(mapTree, in_file, out_file, targetChromSizes, in_format = 'bigwig')
  File "/home/xavier/.local/bin/CrossMap.py", line 1527, in crossmap_wig_file
    for (chr, start, end, score) in bgrMerge.merge(out_prefix + '.bgr'):
  File "/home/xavier/.local/lib/python3.6/site-packages/cmmodule/bgrMerge.py", line 95, in merge
    (last_chr, last_start, last_end, last_score) = lines[-1].split()
IndexError: list index out of range
[bwClose] There was an error while finishing writing a bigWig file! The output is likely truncated.

we had no issue processing bed files from our pipeline.
Any ideas?
thank you

**Comment by igschnei** [comment]
I have the exact same error. Have you ever figured out the solution?

**Comment by liguowang** [comment]
Hi, did you use the most recent version of CrossMap? or is it OK to share the bigwig file so that I can figure out the problem? 

Thanks

Liguo

**Comment by xavdartagnan** [comment]
hi sorry that s a long time I did not use crossmap, at least a year probably more. I ll try to check tomorrow but as I recall it worked only on some bigwig files, not all.lift over works on bed files though.coming back to you tomorrow,bestXavierLe 3 déc. 2020 20:59, Liguo Wang <notifications@github.com> a écrit :
Hi, did you use the most recent version of CrossMap? or is it OK to share the bigwig file so that I can figure out the problem?
Thanks
Liguo

**Comment by xaviercontreras** [comment]
Oops sorry I did not realize I was answering to the forum. I do not think I had found a solution with crossmaps at the time but I see as mentioned above that there is a new version so maybe it now works. Also, make sure you have the wig_to_bigwig file. Good luck, I hope liguo can help you, it is beyond my abilities.
