### ISSUE TITLE
convert bigwig error

### ISSUE THREAD

**Issue by jiangshan529** [liguowang/CrossMap#30]
Hi, I am now using CrossMap.py to convert bigwig format. 
I can successfully convert chlSab2 to hg38,(CrossMap.py bigwig chlSab2ToHg38.over.chain.gz vero.Normalized.bw vero_to_hg38),
but when I convert this hg38 to hg19(CrossMap.py bigwig hg38ToHg19.over.chain.gz vero_to_hg38.bw vero_to_hg19), 
it reports the error: 
TypeError: 'NoneType' object is not iterable
[bwClose] There was an error while finishing writing a bigWig file! The output is likely truncated.

**Comment by jiangshan529** [comment]
> Hi, I am now using CrossMap.py to convert bigwig format.
> I can successfully convert chlSab2 to hg38,(CrossMap.py bigwig chlSab2ToHg38.over.chain.gz vero.Normalized.bw vero_to_hg38),
> but when I convert this hg38 to hg19(CrossMap.py bigwig hg38ToHg19.over.chain.gz vero_to_hg38.bw vero_to_hg19),
> it reports the error:
> TypeError: 'NoneType' object is not iterable
> [bwClose] There was an error while finishing writing a bigWig file! The output is likely truncated.

The full error message is :
2021-06-30 11:21:23 [INFO]  Read the chain file "hg38ToHg19.over.chain.gz" 
2021-06-30 11:21:24 [INFO]  Liftover bigwig file vero_to_hg38.bw to bedGraph file vero_to_hg19.bgr:
Traceback (most recent call last):
  File "/home/baijsh/biosoft/yes/bin/CrossMap.py", line 145, in <module>
    crossmap_wig_file(mapTree, in_file, out_file, targetChromSizes, in_format = 'bigwig')
  File "/home/baijsh/biosoft/yes/lib/python3.8/site-packages/cmmodule/mapwig.py", line 90, in crossmap_wig_file
    for chrom, start, end, score in bigwigReader(in_file):
  File "/home/baijsh/biosoft/yes/lib/python3.8/site-packages/cmmodule/utils.py", line 155, in bigwigReader
    for i_st, i_end, i_score in bw.intervals(chr_name, 0, chr_size):
TypeError: 'NoneType' object is not iterable

**Comment by jiangshan529** [comment]
> Hi, I am now using CrossMap.py to convert bigwig format.
> I can successfully convert chlSab2 to hg38,(CrossMap.py bigwig chlSab2ToHg38.over.chain.gz vero.Normalized.bw vero_to_hg38),
> but when I convert this hg38 to hg19(CrossMap.py bigwig hg38ToHg19.over.chain.gz vero_to_hg38.bw vero_to_hg19),
> it reports the error:
> TypeError: 'NoneType' object is not iterable
> [bwClose] There was an error while finishing writing a bigWig file! The output is likely truncated.

The full error message is:
2021-06-30 11:21:23 [INFO]  Read the chain file "hg38ToHg19.over.chain.gz" 
2021-06-30 11:21:24 [INFO]  Liftover bigwig file vero_to_hg38.bw to bedGraph file vero_to_hg19.bgr:
Traceback (most recent call last):
  File "/home/baijsh/biosoft/yes/bin/CrossMap.py", line 145, in <module>
    crossmap_wig_file(mapTree, in_file, out_file, targetChromSizes, in_format = 'bigwig')
  File "/home/baijsh/biosoft/yes/lib/python3.8/site-packages/cmmodule/mapwig.py", line 90, in crossmap_wig_file
    for chrom, start, end, score in bigwigReader(in_file):
  File "/home/baijsh/biosoft/yes/lib/python3.8/site-packages/cmmodule/utils.py", line 155, in bigwigReader
    for i_st, i_end, i_score in bw.intervals(chr_name, 0, chr_size):
TypeError: 'NoneType' object is not iterable
[bwClose] There was an error while finishing writing a bigWig file! The output is likely truncated.

**Comment by liguowang** [comment]
Please let me know if you can convert the bedgraph (.bgr) file using UCSC’s wigToBigwig. Thanks

Liguo

**Comment by jiangshan529** [comment]
I see, I can successfully cross chlsab.bw to hg38.bw, but when I transfer
hg38.bw to hg19.bw, the generated hg19.bgr file is truncated, it only has
few chromosomes(chr1,chr12,chr6,chr10,chr11). I don't know why.

Liguo Wang ***@***.***> 于2021年6月30日周三 下午11:00写道：

> Please let me know if you can convert the bedgraph (.bgr) file using
> UCSC’s wigToBigwig. Thanks
>
> Liguo
>

**Comment by GrossTor** [comment]
I came across the same error while mapping bigwigs from mm9 to mm10 (mouse assemblies). The issue is that the `intervals` method of the `bw` object in [line 176 in utils](https://github.com/liguowang/CrossMap/blob/5ff8b750abfdeae5fe67dd42bbbf90544531e230/lib/cmmodule/utils.py#L176) returns `None` if the original bigwig file does not contain a coverage track for the chosen chromosome. This happens in my bigwig file for non-canonical chromosomes such as _chr1_random_. My solution was to replace that line with the following

```
intervals = bw.intervals(chr_name, 0, chr_size)
if intervals is None:
	intervals = []
for i_st, i_end, i_score in intervals:
```
I am not certain that this change is robust and will work in all cases. But feel free to incorporate it or ask for a PR @liguowang .

**Comment by liguowang** [comment]
@GrossTor Yes, this will work. Thanks for doing this. I will incorporate the change soon.

**Comment by liguowang** [comment]
@jiangshan529 @GrossTor @bgruening @roryk version 0.6.4 was released. please let us know if this problem persist.
