### ISSUE TITLE
Wrong mapping when conversion from GRCh38 to GRCh37

### ISSUE THREAD

**Issue by samuellawty** [liguowang/CrossMap#39]
I have experienced a problem during conversion of GRCh38 variants to GRCh37. From the sample vcf data, the ID column specifies the CHROM_POS_REF_ALT in GRCh38 format. However, the GRCh37 mapped outcome showed a totally different ref_allele and alt_allele. By referencing the dbSNP from GRCh38 record (https://www.ncbi.nlm.nih.gov/snp/rs1460283170#variant_details), the GRCh37 position should on the fix_patch chromosome 1 instead of the normal chromosome 1, while the ref_allele and alt_allele is not correct neither. 

It is suspected that as this record is on the negative strand, the alt_allele is converted by reverse complement, and the ref_allele is not the same as the reverse-complemented alt-allele, the record is mapped and displayed in output. Yet, this type of records should be omitted and written in the .unmap file. I hope you may advise the scripts to avoid these wrong mappings present in the mapped output file. The files used and wrong-mapping samples are shown below: 

Version used: v0.5.2
Chain file used: `GRCh38_to_GRCh37.chain.gz`
Reference fasta: `vep/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa`
Sample vcf data:
```
#CHROM  POS        ID               REF  ALT  QUAL  FILTER  INFO
1       143272101  1_143427521_G_T  T    A    .     PASS    AC=2;AN=5996;AF=0.000333556
```

**Comment by liguowang** [comment]
This variant was indeed mapp to "HG1287_PATCH" (hg19). Chain file was
attached.

1       143272100 143272101 -> HG1287_PATCH 143958515 143958516

Which chain file did you use?

**Comment by samuellawty** [comment]
My problem encountered is that I have a GRCh38 variant record `1_143427521_G_T` , which I want to convert into GRCh37 format for analysis. The chain file used is from (https://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh38_to_GRCh37.chain.gz). The conversion outcome is `1_143272101_T_A` , where the new ref_allele (T) is neither consistent with the input (G) nor reverse complement of the input (C). As the variant mapping of ref_allele should follow the input ref_allele, I am puzzled by the conversion outcome and questioned about the mapping problems. How can I understand and comprehend the data output?

**Comment by liguowang** [comment]
Update: Using CrossMap version 0.6.1 and the UCSC chain file. This hg38 variant (1_143427521_G_T) was failed to map due to multiple hits. Please see below (from the *.unmap file). 

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       143427521       XXX     G       T       .       .       .       Fail(Multiple_hits)
