### ISSUE TITLE
command not found: CrossMap

### ISSUE THREAD

**Issue by skanwal** [liguowang/CrossMap#64]
Hello,

I have installed CrossMap using pip on MAC and it seemed to have worked:

```
$ pip3 install CrossMap
Collecting CrossMap
  Downloading CrossMap-0.6.6-py3-none-any.whl.metadata (879 bytes)
Collecting cython>=0.17 (from CrossMap)
  Downloading Cython-3.0.8-cp37-cp37m-macosx_10_9_x86_64.whl.metadata (3.2 kB)
Collecting pysam (from CrossMap)
  Downloading pysam-0.22.0-cp37-cp37m-macosx_10_9_x86_64.whl.metadata (1.5 kB)
Collecting bx-python (from CrossMap)
  Downloading bx_python-0.10.0-cp37-cp37m-macosx_10_9_x86_64.whl.metadata (3.0 kB)
Collecting pyBigWig (from CrossMap)
  Downloading pyBigWig-0.3.22.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.9/73.9 kB 2.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from bx-python->CrossMap)
  Downloading numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 4.6 MB/s eta 0:00:00
Downloading CrossMap-0.6.6-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 2.5 MB/s eta 0:00:00
Downloading Cython-3.0.8-cp37-cp37m-macosx_10_9_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 6.1 MB/s eta 0:00:00
Downloading bx_python-0.10.0-cp37-cp37m-macosx_10_9_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.0 MB/s eta 0:00:00
Downloading pysam-0.22.0-cp37-cp37m-macosx_10_9_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 2.2 MB/s eta 0:00:00
Building wheels for collected packages: pyBigWig
  Building wheel for pyBigWig (pyproject.toml) ... done
  Created wheel for pyBigWig: filename=pyBigWig-0.3.22-cp37-cp37m-macosx_10_9_x86_64.whl size=73547 sha256=858f93d8c5d776b5845f27aa37a05b94279dd50bd62c1845f9212f58c24c00c2
  Stored in directory: /Users/kanwals/Library/Caches/pip/wheels/88/c5/de/ac415e34e3af50ca995ce715dd4186761b0ea02e8d8f25bca1
Successfully built pyBigWig
Installing collected packages: pysam, pyBigWig, numpy, cython, bx-python, CrossMap
Successfully installed CrossMap-0.6.6 bx-python-0.10.0 cython-3.0.8 numpy-1.21.6 pyBigWig-0.3.22 pysam-0.22.0
```

Now when I call CrossMap using `$ CrossMap -h`, I get:

```
zsh: command not found: CrossMap
```

Can you please suggest what could be causing it? I can see it being installed under:

```
$ /Users/kanwals/miniconda/envs/crossmap/bin/pip3 install CrossMap
Requirement already satisfied: CrossMap in /Users/kanwals/miniconda/envs/crossmap/lib/python3.7/site-packages (0.6.6)
```

**Comment by liguowang** [comment]
The "CrossMap" command is typically installed in the directory where your "python" executable is located. Below is an example of installing CrossMap on my Mac.

_# create a virtual environment called test_
`conda create -n test`

_# activate this environment_
`conda activate test`

`$ which python3`
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3

`$ which pip3`
/Library/Frameworks/Python.framework/Versions/3.11/bin/pip3

`$ pip3 install CrossMap`
Collecting CrossMap
  Downloading CrossMap-0.7.0-py3-none-any.whl.metadata (4.5 kB)
Collecting pysam (from CrossMap)
  Downloading pysam-0.22.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: bx-python in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from CrossMap) (0.10.0)
Collecting pyBigWig (from CrossMap)
  Using cached pyBigWig-0.3.22.tar.gz (73 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from bx-python->CrossMap) (1.26.3)
Downloading CrossMap-0.7.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 426.8 kB/s eta 0:00:00
Downloading pysam-0.22.0-cp311-cp311-macosx_10_9_x86_64.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 2.5 MB/s eta 0:00:00
Building wheels for collected packages: pyBigWig
  Building wheel for pyBigWig (pyproject.toml) ... done
  Created wheel for pyBigWig: filename=pyBigWig-0.3.22-cp311-cp311-macosx_10_9_universal2.whl size=121899 sha256=02a97a753f0d4887d65f7278828b0fc8c542af8ba740816345d11dd763322a92
  Stored in directory: /Users/m102324/Library/Caches/pip/wheels/e8/f3/f2/56add2ed09ffa03789ad86dd3b1795ce6f27a09b53b3fef945
Successfully built pyBigWig
Installing collected packages: pysam, pyBigWig, CrossMap
Successfully installed CrossMap-0.7.0 pyBigWig-0.3.22 pysam-0.22.0

`$ which CrossMap`
/Library/Frameworks/Python.framework/Versions/3.11/bin/CrossMap

`$ CrossMap -h`
usage: CrossMap [-h] [-v] {bed,bam,gff,wig,bigwig,vcf,gvcf,maf,region,viewchain} ...

CrossMap (v0.7.0) is a program to convert (liftover) genome coordinates between different reference assemblies (e.g., from human GRCh37/hg19 to GRCh38/hg38 or vice versa). Supported file formats: BAM,
BED, BigWig, CRAM, GFF, GTF, GVCF, MAF (mutation annotation format), SAM, Wiggle, and VCF.

positional arguments:
  {bed,bam,gff,wig,bigwig,vcf,gvcf,maf,region,viewchain}
                        sub-command help
  ...

**Comment by skanwal** [comment]
Thanks @liguowang for the quick response.

In my case, the pip within the conda environment was interfering with the system's pip installation.
I went down the conda way - installing https://anaconda.org/bioconda/crossmap worked for me both locally and on cluster.
